FROM node:20-alpine AS builder

WORKDIR /app

RUN npm install -g pm2

COPY src/server/package*.json ./

RUN npm install

COPY src/server/ ./

FROM node:20-alpine

WORKDIR /app

COPY --from=builder /usr/local/bin/pm2 /usr/local/bin/pm2
COPY --from=builder /usr/local/lib/node_modules/pm2 /usr/local/lib/node_modules/pm2

COPY --from=builder /app/node_modules ./node_modules
COPY src/server/ ./

EXPOSE 3000

CMD ["pm2-runtime", "server.js"]